containerBuild:
  imageName: maps-ai-script-helper

deployment: 
  name: maps-ai-script-helper
  namespace: maps-data-analysis
  strategy: Recreate
  cpu: 250m
  limitCpu: 1000m
  memory: 512Mi 
  limitMemory: 2Gi
  replicas: 1
  containerPort: 8080
  healthCheckPath: /health
  healthCheckPort: 8080
  healthCheckType: 'http'
  ingressPath: /
  iamRole: tfstack-maps-data-analysis
  serviceAccount: tfstack-maps-data-analysis
  labels:
    stack: python
    component: backend
    sub_application: maps-ai-script-helper
    part_of: greg.clark
    stack_version: 1.0
    application_owner: greg.clark2@thermofisher.com
    costcenter: 1100369R_MSHILLSBORO 
    website: www.thermofisher.com
    type: commerce

environments:
  dev:
    branch: main
    cluster: tfcom-cluster-naw-rapidqa1.cloudqa.thermofisher.net
    ingressDomains:
      - maps-ai-script-helper.tfcom-cluster-naw-rapidqa1.cloudqa.thermofisher.net
    deployment:
        volumeMounts:
        - name: outputs
          mountPath: /app/outputs
          volume:
            type: persistentVolumeClaim
            properties:
              claimName: maps-outputs         
        # Library volume removed - using library images baked into image
        - name: assets
          mountPath: /app/assets
          volume:
            type: persistentVolumeClaim
            properties:
              claimName: maps-assets          
        - name: logs
          mountPath: /app/logs
          volume:
            type: persistentVolumeClaim
            properties:
              claimName: maps-logs          
        - name: deploy
          mountPath: /deploy
          volume:
            type: persistentVolumeClaim
            properties:
              claimName: maps-deploy          
        # - name: user-jobs
        #   mountPath: /app/user_jobs.json
        #   subPath: user_jobs.json
        #   volume:
        #     type: persistentVolumeClaim
        #     properties:
        #       claimName: maps-jobs          
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TZ
      value: "America/Los_Angeles"
    - name: KUBERNETES_NAMESPACE
      value: "maps-data-analysis"
    - name: RUNNER_IMAGE
      value: "py-exec:latest"
    - name: SCRIPT_TIMEOUT
      value: "600"
    - name: DATABASE_PATH
      value: "/deploy/maps_helper.db"
    - name: SKIP_AUTO_SEED
      value: "false"  # Auto-seed database with library scripts on startup
    - name: GOOGLE_API_KEY
      key: GOOGLE_API_KEY
      secretname: maps-data-analysis-ai-api-keys
    - name: OPENAI_API_KEY
      key: OPENAI_API_KEY
      secretname: maps-data-analysis-ai-api-keys
